# Generated by Django 5.2.5 on 2025-08-19 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_emails', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('show_email_publicly', models.BooleanField(default=False)),
                ('show_phone_number_publicly', models.BooleanField(default=False)),
                ('show_date_of_birth_publicly', models.BooleanField(default=False)),
                ('show_profile_image_publicly', models.BooleanField(default=False)),
                ('show_full_name_publicly', models.BooleanField(default=False)),
                ('show_last_login', models.BooleanField(default=False)),
                ('show_date_joined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
